version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  include_patterns = ["src/**", "components/**", "**/*.astro"]
  exclude_patterns = ["node_modules/**", "dist/**", "build/**"]