version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
runtime_version = "18"
include_patterns = ["src/**", "components/**", "**/*.astro"]
exclude_patterns = ["node_modules/**", "dist/**", "build/**"]

# Puedes ajustar reglas específicas (transformers)
[transformers]
# Ejemplo para desactivar alguna regla (opcional):
# "javascript.remove-unused-variables" = false